---
- name: Install docker
  hosts: app

  become_method: su
  become_user: root
  become_flags: '-s /bin/sh'

  - name: Install required system packages
    become: true
    package:
     name: {{ item }} 
     state: present
     with_items: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: true
    apt: update_cache=no name=docker-ce state=latest

  - name: Install Docker Module for Python
    become: true
    pip:
      name: docker
