---
- name: Install Selenium
  hosts: Jenkins-Slave

  become_method: su
  become_user: root
  become_flags: '-s /bin/sh'

  tasks:
  - name: Update APT package manager repositories cache
    become: true
    apt:
      update_cache: no

  - name: Install aptitude using apt
    become: true
    apt: name=aptitude state=latest update_cache=no force_apt_get=no

  - name: Install required system packages
    become: true
    apt: name={{ item }} state=latest update_cache=no
    with_items: [ 'xvfb', 'libgconf-2-4']

  - name: Add Google Chrome Key
    become: true
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present

  - name: Add Google Repo
    become: true
    apt_repository:
      repo: deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: Update apt and install Google Chrome
    become: true
    apt: update_cache=no name=google-chrome-stable state=latest

  - name: Install Chrome Driver
    action: shell cd /home/suresh && mkdir -p chrome-modules && cd chrome-modules && wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip && unzip chromedriver_linux64.zip

  - name: Update Chrome Driver Path
    become: true
    action: shell mv chromedriver /usr/bin/chromedriver && chown root:root /usr/bin/chromedriver && chmod +x /usr/bin/chromedriver

  - name: Download Selenium JARs
    action: shell wget http://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar && wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip && unzip testng-6.8.7.jar.zip
